#!/bin/bash

if [ -z $1 ] ; then
    flock /var/lock/recopy.lock echo -n "mv \"$(pwd)/\"* " > /var/lock/recopy.lock
else
    if [ ! -f $(pwd)/$1 ] && [ ! -d $(pwd)/$1 ]; then
        echo "File not found!"
    else
        flock /var/lock/recopy.lock echo -n "mv \"$(pwd)/$1\" " > /var/lock/recopy.lock
    fi
fi
